# creation rules are evaluated sequentially, the first match wins
creation_rules:
        - path_regex: local\.enc\.json$
          azure_keyvault: https://rmicredsrvlocalsops.vault.azure.net/keys/sops/8c544f0ae62b4d5a9b1c7ef755345f22

