# creation rules are evaluated sequentially, the first match wins
creation_rules:
        - path_regex: cmd/server/configs/allowlists/dev\.enc\.json$
          azure_keyvault: https://rmicredsrvdevsops.vault.azure.net/keys/sops/2e4989d46cb24ccb96c8ce98e9104fe5

